from django.urls import path
from . import api

urlpatterns = [
    path(
        'initial_examinations/create/',
        api.initial_examination_create,
        name='initial_examination_create'
    ),

    path(
        'initial_examinations/<uuid:patient_id>/',
        api.initial_examination_list,
        name='initial_examination_list'
    ),

    path(
        'instruction_wearables/create/',
        api.instruction_wearables_create,
        name='instruction_wearables_create'
    ),
    path('instruction_wearables/<uuid:patient_id>/',
         api.instruction_wearables_list,
         name='instruction_wearables_list'
         ),

    path(
        'initial_interview_telephones/create/',
        api.initial_interview_telephones_create,
        name='initial_interview_telephones_create'
    ),
    path(
        'initial_interview_telephones/<uuid:patient_id>/',
        api.initial_interview_telephones_list,
        name='initial_interview_telephones_list'
    ),

    path(
        'data_review_processing/create/',
        api.data_review_processing_create,
        name='data_review_processing_create'
    ),
    path(
        'data_review_processing/<uuid:patient_id>/',
        api.data_review_processing_list,
        name='data_review_processing_list'
    ),

    path(
        'telephone_consultations/create/',
        api.telephone_consultations_create,
        name='telephone_consultations_create'
    ),
    path(
        'telephone_consultations/<uuid:patient_id>/',
        api.telephone_consultations_list,
        name='telephone_consultations_list'
    ),
    path(
        'consultation_reason_choices/',
        api.consultation_reason_choices,
        name='consultation_reason_choices'
    ),
    path(
        'feedback_care_team_telephone_consultation/create/',
        api.feedback_care_team_telephone_consultation_create,
        name='feedback_care_team_telephone_consultation_create'
    ),
    path(
        'feedback_care_team_telephone_consultation/<uuid:patient_id>/',
        api.feedback_care_team_telephone_consultation_list,
        name='feedback_care_team_telephone_consultation_list'
    ),
    path(
        'feedback_care_team_telephone_consultation_choices/',
        api.feedback_care_team_telephone_consultation_choices,
        name='feedback_care_team_telephone_consultation_choices'
    ),
    path(
        'case_review_nurse_council/create/',
        api.case_review_nurse_council_create,
        name='case_review_nurse_council_create'
    ),
    path(
        'case_review_nurse_council/<uuid:patient_id>/',
        api.case_review_nurse_council_list,
        name='case_review_nurse_council_list'
    ),
    path(
        'case_review_council/create/',
        api.case_review_council_create,
        name='case_review_council_create'
    ),
    path(
        'case_review_council/<uuid:patient_id>/',
        api.case_review_council_list,
        name='case_review_council_list'
    ),
    path(
        'case_review/create/',
        api.case_review_create,
        name='case_review_create'
    ),
    path(
        'case_review/<uuid:patient_id>/',
        api.case_review_list,
        name='case_review_list'
    ),
    path(
        'consultation/create/',
        api.consultation_create,
        name='consultation_create'
    ),
    path(
        'consultation/<uuid:patient_id>/',
        api.consultation_list,
        name='consultation_list'
    ),
    path(
        'visit/create/',
        api.visit_create,
        name='visit_create'
    ),
    path(
        'visit/<uuid:patient_id>/',
        api.visit_list,
        name='visit_list'
    ),
    path(
        'equipment/create/',
        api.equipment_create,
        name='equipment_create'
    ),
    path(
        'equipment/<uuid:patient_id>/',
        api.equipment_list,
        name='equipment_list'
    ),

]
