from django.urls import path
from . import api

urlpatterns = [
    path(
        'initial_examinations/',
        api.InitialExaminationListCreateAPIView.as_view(),
        name='initial_examinations_list_create'
    ),
    path(
        'initial_examinations/<uuid:pk>/',
        api.InitialExaminationRetrieveUpdateDestroy.as_view(),
        name='initial_examinations_retrieve_update_destroy'
    ),

    path(
        'instruction_wearables/',
        api.InstructionWearableListCreate.as_view(),
        name='instruction_wearables_list_create'
    ),
    path('instruction_wearables/<uuid:pk>/',
         api.InstructionWearableRetrieveUpdateDestroy.as_view(),
         name='instruction_wearables_retrieve_update_destroy'
         ),

    path(
        'initial_interview_telephones/',
        api.InitialInterviewTelephoneListCreate.as_view(),
        name='initial_interview_telephones_list_create'
    ),
    path(
        'initial_interview_telephones/<uuid:pk>/',
        api.InitialInterviewTelephoneRetrieveUpdateDestroy.as_view(),
        name='initial_interview_telephones_retrieve_update_destroy'
    ),

    path(
        'data_review_processings/',
        api.DataReviewProcessingListCreate.as_view(),
        name='data_review_processings_list_create'
    ),
    path(
        'data_review_processings/<uuid:pk>/',
        api.DataReviewProcessingRetrieveUpdateDestroy.as_view(),
        name='data_review_processings_retrieve_update_destroy'
    ),

    path(
        'telephone_consultations/',
        api.TelephoneConsultationListCreate.as_view(),
        name='telephone_consultations_list_create'
    ),
    path(
        'telephone_consultations/<uuid:pk>/',
        api.TelephoneConsultationRetrieveUpdateDestroy.as_view(),
        name='telephone_consultations_retrieve_update_destroy'
    ),
    path(
        'feedback_careTeam_telephone_consultation/',
        api.FeedbackCareTeamTelephoneConsultationListCreate.as_view(),
        name='feedback_careTeam_telephone_consultation_list_create'
    ),
    path(
        'feedback_careTeam_telephone_consultation/<uuid:pk>/',
        api.FeedbackCareTeamTelephoneConsultationRetrieveUpdateDestroy.as_view(),
        name='feedback_careTeam_telephone_consultation_retrieve_update_destroy'
    ), path(
        'case_review_nurse_council/',
        api.CaseReviewNurseCouncilListCreate.as_view(),
        name='case_review_nurse_council_list_create'
    ),
    path(
        'case_review_nurse_council/<uuid:pk>/',
        api.CaseReviewNurseCouncilRetrieveUpdateDestroy.as_view(),
        name='case_review_nurse_council_retrieve_update_destroy'
    ),
    path(
        'case_review_council/',
        api.CaseReviewCouncilListCreate.as_view(),
        name='case_review_council_list_create'
    ),
    path(
        'case_review_council/<uuid:pk>/',
        api.CaseReviewCouncilRetrieveUpdateDestroy.as_view(),
        name='case_review_council_retrieve_update_destroy'
    ),
    path(
        'case_review/',
        api.CaseReviewListCreate.as_view(),
        name='case_review_list_create'
    ),
    path(
        'case_review/<uuid:pk>/',
        api.CaseReviewRetrieveUpdateDestroy.as_view(),
        name='case_review_retrieve_update_destroy'
    ),
    path(
        'consultation/',
        api.ConsultationListCreate.as_view(),
        name='consultation_list_create'
    ),
    path(
        'consultation/<uuid:pk>/',
        api.ConsultationRetrieveUpdateDestroy.as_view(),
        name='consultation_retrieve_update_destroy'
    ),
    path(
        'visit/',
        api.VisitListCreate.as_view(),
        name='visit_list_create'
    ),
    path(
        'visit/<uuid:pk>/',
        api.VisitRetrieveUpdateDestroy.as_view(),
        name='visit_retrieve_update_destroy'
    ),
    path(
        'equipment/',
        api.EquipmentListCreate.as_view(),
        name='equipment_list_create'
    ),
    path(
        'equipment/<uuid:pk>/',
        api.EquipmentRetrieveUpdateDestroy.as_view(),
        name='equipment_retrieve_update_destroy'
    ),

]
