# Generated by Django 4.2.2 on 2023-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_bloodcholesterolmeasurementcomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='unit',
            field=models.CharField(default='mmHg', max_length=30),
        ),
        migrations.AlterField(
            model_name='heartratemeasurement',
            name='unit',
            field=models.CharField(default='bpm', max_length=30),
        ),
        migrations.AlterField(
            model_name='respirationratemeasurement',
            name='unit',
            field=models.CharField(default='breaths per minute', max_length=30),
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='unit',
            field=models.CharField(default='°C', max_length=30),
        ),
    ]
