# Generated by Django 4.2.2 on 2023-07-08 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor', '0003_alter_bloodpressuremeasurement_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurementcomments',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurementcomments',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurementcomments',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurementcomments',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurementcomments',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurementcomments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurementcomments',
            name='measurement',
        ),
        migrations.AddField(
            model_name='bloodcholesterolmeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodglucosemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodpressuremeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartratemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinsonsmeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respirationratemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodcholesterolmeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodglucosemeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heartratemeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkinsonsmeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respirationratemeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BloodCholesterolMeasurementComments',
        ),
        migrations.DeleteModel(
            name='BloodGlucoseMeasurementComments',
        ),
        migrations.DeleteModel(
            name='BloodPressureMeasurementComments',
        ),
        migrations.DeleteModel(
            name='HeartRateMeasurementComments',
        ),
        migrations.DeleteModel(
            name='ParkinsonsMeasurementComments',
        ),
        migrations.DeleteModel(
            name='RespirationRateMeasurementComments',
        ),
        migrations.DeleteModel(
            name='TemperatureMeasurementComments',
        ),
        migrations.AddField(
            model_name='bloodcholesterolmeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='bloodglucosemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='bloodpressuremeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='heartratemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='parkinsonsmeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='respirationratemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comments'),
        ),
    ]
