# Generated by Django 4.2.2 on 2023-07-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcholesterolmeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodcholesterolmeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='comments_count',
        ),
        migrations.AlterField(
            model_name='bloodcholesterolmeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodglucosemeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heartratemeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkinsonsmeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respirationratemeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temperaturemeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
