# Generated by Django 4.2.2 on 2023-07-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor', '0006_alter_bloodcholesterolmeasurement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcholesterolmeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodglucosemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodpressuremeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartratemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinsonsmeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respirationratemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bloodcholesterolmeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='bloodglucosemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='bloodpressuremeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='heartratemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='parkinsonsmeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='respirationratemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
        migrations.AddField(
            model_name='temperaturemeasurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sensor.comment'),
        ),
    ]
