# Generated by Django 4.2.2 on 2023-07-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_bloodcholesterolmeasurement_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcholesterolmeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodcholesterolmeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodglucosemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bloodpressuremeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='heartratemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='parkinsonsmeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='respirationratemeasurement',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='temperaturemeasurement',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
