# Generated by Django 4.2.2 on 2023-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='PLZ',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='city', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nr',
            field=models.CharField(default=12, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='street', max_length=200),
            preserve_default=False,
        ),
    ]
