# Generated by Django 4.2.2 on 2023-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_address_patient_plz_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reason_of_visiting',
            field=models.TextField(blank=True),
        ),
    ]
