# Generated by Django 4.2.2 on 2023-07-12 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_remove_bloodglucosemeasurement_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(blank=True, max_length=10)),
                ('removed_at', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('visit_reason', models.TextField(blank=True)),
                ('misc_documentation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, max_length=255, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('consultation_reason', models.CharField(blank=True, choices=[(1, 'Besprechung einer Verschlechterung/ Veränderung'), (2, 'Kontaktwunsch der/ des Patient*in'), (3, 'Unregelmäßige Nutzung des Monitorings'), (4, 'Nachbesprechung Pflegekonsil'), (5, 'Nachbesprechung zu Empfehlung/en (nach 14 Tagen)'), (6, 'Folgetelefonat nach Krankenhausaufenthalt '), (7, 'Follow-up - 2 Monate keine Verschlechterung'), (8, 'Freitext - Sonstige Inhalte, und zwar: ')], max_length=5)),
                ('conversation_topics', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('recommendation_issued', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
                ('consultation_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionWearable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('centre_pick', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialInterviewTelephone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('conversation_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialExamination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('centre_pick', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackCareTeamTelephoneConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback_necessary', models.BooleanField(default=False)),
                ('feedback_questions', models.TextField(blank=True)),
                ('feedback_to', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Facharzt', 'Facharzt'), ('extern', 'extern')], max_length=225)),
                ('recommendations', models.TextField(blank=True)),
                ('visit_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DataReviewProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('duration_month', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor_initials', models.CharField(blank=True, max_length=255)),
                ('decisions', models.TextField(blank=True)),
                ('reason_for_admission', models.TextField(blank=True)),
                ('hospital_admission_required', models.BooleanField(default=False)),
                ('clinic_appointment_required', models.BooleanField(default=False)),
                ('reason_for_clinic_appointment', models.TextField(blank=True)),
                ('measures_after_appointment', models.TextField(blank=True)),
                ('measures_taken', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseReviewNurseCouncil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('second_visit_required', models.BooleanField(default=False)),
                ('discussed_issues', models.TextField(blank=True)),
                ('specialist_consultation_required', models.BooleanField(default=False)),
                ('recommendations', models.TextField(blank=True)),
                ('recommendation_issued', models.TextField(blank=True)),
                ('anamnese_discussed', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, max_length=255, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseReviewCouncil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('anamnese_discussed', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, max_length=255, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('documentation_role', models.CharField(blank=True, choices=[('Parkinson Nurse', 'Parkinson Nurse'), ('TeleNurse', 'TeleNurse'), ('Pflegedienst', 'Pflegedienst'), ('Neurologen', 'Neurologen')], max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('anamnese_discussed', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, max_length=255, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
