# Generated by Django 4.2.2 on 2023-07-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_casereview_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialexamination',
            old_name='centre_pick',
            new_name='centrePick',
        ),
        migrations.RenameField(
            model_name='instructionwearable',
            old_name='centre_pick',
            new_name='centrePick',
        ),
    ]
