# Generated by Django 4.2.2 on 2023-07-22 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_bloodglucosemeasurement_patient_and_more'),
        ('documentation', '0005_casereview_note_casereviewcouncil_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='patient',
            field=models.ForeignKey(default='3f01bb35-f340-4b66-8777-d43d538d6b9c', on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
