# Generated by Django 4.2.2 on 2023-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_equipment_patient_alter_equipment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='removed_at',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
