# Generated by Django 4.2.2 on 2023-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_remove_equipment_created_at_remove_equipment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='removed_at',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
