# Generated by Django 4.2.2 on 2023-07-22 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_bloodglucosemeasurement_patient_and_more'),
        ('documentation', '0008_equipment_created_at_equipment_removed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
