# Generated by Django 4.2.2 on 2023-07-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0009_equipment_patient_alter_equipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='equipment',
            name='note',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
