# Generated by Django 4.2.2 on 2023-07-23 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_remove_bloodglucosemeasurement_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarthelIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barthel_food', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'Hilfe bei der Vorbereitung notwendig'), (10, 'komplett selbstständig')])),
                ('barthel_wash', models.IntegerField(choices=[(0, 'keine Selbstständigkeit gegeben'), (5, 'komplett selbstständig')])),
                ('barthel_shower', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'Hilfe bei der Vorbereitung notwendig')])),
                ('barthel_dress', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'selbständig bei Oberkörper/ nutzt Utensilien'), (10, 'komplett selbstständig')])),
                ('barthel_stool', models.IntegerField(choices=[(0, 'kontinent oder komplett selbstständige Versorgung'), (5, 'überwiegend selbständige Versorgung'), (10, 'kontinent oder komplett selbstständige Versorgung')])),
                ('barthel_urin', models.IntegerField(choices=[(0, 'kontinent oder komplett selbstständige Versorgung'), (5, 'überwiegend selbständige Versorgung'), (10, 'kontinent oder komplett selbstständige Versorgung')])),
                ('barthel_wc', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'Hilfe bei der Vorbereitung notwendig'), (10, 'komplett selbstständig')])),
                ('barthel_transf', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'erhebliche Hilfe oder Aufsicht nötig'), (10, 'geringe Hilfe oder Aufsicht nötig'), (15, 'komplett selbstständig')])),
                ('barthel_walk', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'mit Laienhilfe/ Gehwagen oder bei Rollstuhlnutzung'), (10, 'mit Gehwagen möglich'), (15, 'Aufstehen + 50m ohne Hilfe')])),
                ('barthel_staris', models.IntegerField(choices=[(0, 'ohne Hilfe nicht durchführbar'), (5, 'Hilfe bei einem Stockwerk notwendig'), (10, 'komplett selbstständig 1 Stockwerk auf und ab')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
